### ISSUE TITLE
Freely deletable notes? Seriously?

### ISSUE THREAD

**Issue by ubergeek77** [RetroAchievements/RAIntegration#115]
I wanted to get started on developing achievements for a game, and there was some clutter I wanted to get rid of in the Memory Inspector notes. What _**wasn't made perfectly clear**_ is that, when a note is deleted, _**it deletes that note for ALL developers**_ as it syncs this change to the server immediately. I created a new RetroAchievements account to test this, and sure enough, those notes are gone. It is eluded to in the documentation, but it is glazed over, and certainly isn't made as urgently clear as it should be.

One, single button, makes this change. All I have to do it click the "delete" button, and BOOM, note gone.

There are _**NO**_ warnings. _**Zero**_ indication that I may be screwing over other developers by doing this. Yes, I could save my own bookmarks, but the current UX doesn't make this immediately clear or easy to do. Using notes as though they are bookmarks is much more convenient. I can still see a JSON with usernames and addresses in XYZ-Notes2.txt, but the text content of the "notes" field is empty in all of them.

I realize this is an unpaid, open-source hobby project, but quite frankly, this is unacceptable.

At the absolute minimum, users should be shown a warning that makes it very clear that deleting and saving notes will do the same for other developers. But this won't stop trolls from going through a bunch of games and deleting notes, or even **creating fake notes to waste people's time.** This is the internet. Stuff like this will absolutely happen.

As for long term fixes, the default server behavior shouldn't be "overwrite" as it currently is. There are many ways to go about this, but one of them is to do the following:

- _Always_ keep a local copy of locally-created notes. These will override any notes downloaded from the server. This also prevents notes from being lost in the event they are deleted from the RA server.
- On the server-side, save notes on a **per-account** basis, not a per-game basis. This handles accidental deletion of notes for _literally everyone creating achievements._

In this setup, I believe the default behavior should be for RAIntegration to NOT download notes by default. Instead, a "download online notes" button should be implemented, or something to that effect. Then, when this button is clicked:

1. Query the server to retrieve a list of **users** that have notes for a given game.
2. Download separate lists of notes for those users.
3. Combine the two lists, using the address as the unique key
4. When a duplicate is found, ask the user which of the two they would like to keep.
5. Combine this new, combined list with the local list of notes, if any. Then, either use the local list of notes to override any found in this new list (as suggested above), or ask the user once again which of the two they want to use.

I'm sure this could be fleshed out more. But there really needs to be a discussion about this.

As a side note, does retroachievements.org keep server-side backups of notes? If so, I'd like to request that a certain game be restored to a previous state...

**Comment by kdecks** [comment]
Thanks for bringing this up, and it's well thought out. Still It has almost never presented itself as a problem because notes are all saved locally. In the rare cases of vandalism one can connect with other devs or users who have the an earlier version of the file and get the notes again.

One good aspect of the system in place is that there's a master note that ideally has the most accurate info, rather than multiple lists. It's also very simple, I mean that as a good thing.

What I would prefer to see is a viewable permanent history of all addresses with notes, and the ability to save any point of that history as the master note. Ideally as unobtrusively as possible.

Related: #21 (Ability to develop achievements offline).

**Comment by ubergeek77** [comment]
Thanks for the response - I'm glad I got a discussion going. There's one thing I'm not sure about, though:

> Still It has almost never presented itself as a problem because notes are all saved locally. In the rare cases of vandalism one can connect with other devs or users who have the an earlier version of the file and get the notes again.

Are you sure about this? Yes, there is a local text file, however it seems this is silently overwritten with what the server considers to be "up-to-date." I have a local file, but as I mentioned, all previous notes now have an empty string under the "Notes" key. Won't this be overwritten the next time a dev opens an emulator with RAIntegrations? My main frustration with the current system is that there's no confirmation when the local file is modified or overwritten.

Regardless, if you know of a way I can get those notes back, such as finding a file on my system I'm not aware of, I'm all ears. I feel horrible for deleting all those notes...

**Comment by kdecks** [comment]
It's possible to do, but not by design thus it requires using an exploit (and a more professional solution would be better) : Replace the file, log-in. disconnect from the internet, load the game, reconnect to the internet, and then resave each code note to the server. 

This prevents downloading a file of empty notes for the server, which happens when you load up the game. It's only not a pain because vandalism of notes has been very rare.

Perhaps jump on Discord and we can see if we can find someone who has a copy of the notes.

**Comment by ubergeek77** [comment]
Thanks! I'll keep this in mind for the future if anything bad happens to my notes.

I can't get on Discord with this immediately (perhaps tomorrow), but for the record, the game I "vandalized" is Boktai, game ID 568:

https://retroachievements.org/game/568

I spent some time today creating and uploading as many as I could to replace the ones I lost (adding some more detail to each), and those have already been uploaded to the RA server. Although there are definitely some missing from what was previously in the notes that I'm not sure how to find. Hopefully someone has a copy, or at the very least, no one is upset that their notes are gone.

**Comment by kdecks** [comment]
In that case send a PM to fitzg

**Comment by Jamiras** [comment]
I've added a confirmation to note deleting.

I don't believe there's any plans to support per-user code notes. Notes apply to the game and sharing them across all users would ensure something found by one user would be available to all users. 

I believe having an audit log could help track changes to notes, but I'm not sure if it makes more sense to do so per note, or just per game. In either case, that would be a server-side feature and should be written up in the RAWeb repository.

Offline support is a separate topic and should mimic online behavior. The only difference is the changes would be queued and submitted at a later time.

Something else that will help with this issue is more granular permissions. A general user might not even be able to see notes. A beginning developer could see notes, add notes, and edit/delete their own notes, but not other's notes. A trusted developer could edit/delete anyone's notes.

I don't see any more integration work to be done for this ticket at this time. I'm going to close it.
