### ISSUE TITLE
Bug, RAVBA: Rich Presence Monitor does not display unicode

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RAIntegration#182]
As a developer who likes to make detailed rich presence I love the Rich Presence Monitor. Currently the Rich Presence Monitor does not display unicode characters like other RA-emulators do. If possible, putting in unicode support would aide in rich presence development on RAVBA.

**Comment by Jamiras** [comment]
The support is there, it's just a side effect of however RAVBA initializes its Windows subsystem. It's probably the same root cause as the different header styles seen when viewing the Achievements List or Achievement Editor in RAVBA vs. the other emulators.

Note: RAVBA, RAGens, RAMeka, and RALibRetro all show the alternate header style. RANes, RASnes9x, and RAProject64 show the intended header style.

**Comment by Jamiras** [comment]
RASNES9x visual style:
![image](https://user-images.githubusercontent.com/32680403/52019880-76f12200-24ac-11e9-9f94-1efa1a30ad7c.png)

RAVBA visual style:
![image](https://user-images.githubusercontent.com/32680403/52019899-8a9c8880-24ac-11e9-9d64-ef20edbef507.png)

Same code running in both.
