### ISSUE TITLE
Master causes crashes when activating cloned achievements

### ISSUE THREAD

**Issue by rzumer** [RetroAchievements/RAIntegration#218]
Regression since the last release (https://github.com/RetroAchievements/RAIntegration/commit/00f0be54b8432d1f5ba995e40039e9e6722f4d70), `RAIntegration` causes emulators to crash and reportedly fail to process achievements. Easy to reproduce with `RAQUASI88` (https://github.com/rzumer/quasi88/tree/feature/cheevos, or compiled with `RAIntegration` master [here](https://0x0.st/sdep.zip)) which calls the interface with no pre-processing, by creating or cloning a few achievements and activating one down the list.

One user reports that "after activation i have to click on a value or something to get [the second achievement in the list] running" and that "it just stays active and tries to submit every frame".

**Comment by Jamiras** [comment]
Going to need more details than that. 

I was able to successfully trigger the Shrroooms achievement using the first zip you provided in discord, which as far as I'm aware is the same build the "one user" was reporting against.

![image](https://user-images.githubusercontent.com/32680403/50380830-33480480-0632-11e9-8b92-673fea60f4f2.png)

This build did not display an achievement popup, and the trigger sound is a beep because the zip file does not contain the overlay subdirectory where the custom wav files exist.

The second zip file (which reverts to an older RAIntegration.dll) behaves the same way.

The third file (raw exe) was rejected by my virus scanner.

**Comment by Jamiras** [comment]
I am unable to reproduce the repeated activation/sound using the original zip/dll or the newest zip/current master dll. The newest executable does show the popup, and I see what you mean about the screen not rendering over it. It seems like the emulator is not painting the window every frame.

I'm going to use this ticket to fix the null reference when activating a cloned achievement. If you believe the other issue is still a problem, please create a new ticket with steps to reproduce.

**Comment by rzumer** [comment]
I didn't say anything about rendering. But OK with dropping this part of the issue - changed the title to reflect this.

**Comment by Jamiras** [comment]
Rendering was mentioned in the other ticket:
> I have not yet been able to solve the flickering and "trailing" (i.e. the overlay leaving a mark when the emulator is not rendering over it).

I didn't intend to intertwine the tickets, I was just commenting that the newest build is the first one I saw any overlay.
