### ISSUE TITLE
Offload more responsibility for the overlay to RAIntegration

### ISSUE THREAD

**Issue by rzumer** [RetroAchievements/RAIntegration#219]
Right now emulators have too much responsibility over the overlay and it must be drawn along with every frame from within the draw loop with proper timing. It leaves too much room for error in my opinion, is not compatible with the draw methods of every emulator, and is potentially unstable without being isolated in a separate surface from the main window. It would be preferable for the overlay to be independent of emulator timing and for any extra overlaid surface to be created from within RAIntegration instead of being a responsibility of the emulator.

If there is a reliable way to get the display working without introducing extra dependencies to create overlaid surfaces or lots of boilerplate, then example code would be useful in the meantime.

**Comment by Jamiras** [comment]
I'm not disagreeing with any of those points, it's just what we have to deal with right now. 

The currently released DLL renders the overlay directly to a DeviceContext using GDI calls. A lot of work has gone into the as-of-yet unreleased version to render to a bitmap, then blit to the GDI surface. 

Future work will expose the ability to render to other surfaces. RALibRetro has flickering issues currently because we can't render the overlay directly to the SDL surface (https://github.com/RetroAchievements/RALibretro/issues/3).

**Comment by rzumer** [comment]
>A lot of work has gone into the as-of-yet unreleased version to render to a bitmap, then blit to the GDI surface.

That sounds like a good improvement. I personally dealt with implementing it into `RAQUASI88` and I have not yet been able to solve the flickering and "trailing" (i.e. the overlay leaving a mark when the emulator is not rendering over it).

**Comment by Jamiras** [comment]
Overlay elements are now rendered in a transparent window floating above the emulator window. This ensures that the overlay elements can be rendered independently from the emulator's rendering implementation.

This also changes the interaction between the emulator and the toolkit - the emulator now only needs to provide inputs when the overlay flyout is open. Psuedo-code:

```
if (RA_IsOverlayFullyVisible()) {
    ControllerInput input;
    // populate input structure
    RA_NavigateOverlay(&input);
}
```

The emulator no longer needs to calculate the time between rendering frames or erase/repaint portions of the screen previously covered by the overlays.
