### ISSUE TITLE
Do not prompt to update on GITRELEASE version

### ISSUE THREAD

**Issue by rzumer** [RetroAchievements/RAIntegration#229]
Standalone emulators have version numbers generated automatically, but for RALibretro it is `GITRELEASE` by default. The new version prompt should not appear, unless there is a reason for it.

**Comment by Jamiras** [comment]
This should have been created in the RALibretro repository, and the problem is that the file is currently generated by a makefile - it's not part of the Visual Studio process. https://github.com/RetroAchievements/RALibretro/blob/develop/Makefile#L74-L76

**Comment by rzumer** [comment]
Would it be possible to ignore version strings that don't contain numbers, or don't correspond to the standard pattern? I can file a corresponding issue in the `RALibretro` repository otherwise.

**Comment by Jamiras** [comment]
Apparently there is a batch file in the VS build, but it's only generating the hash property. I've updated it to also generate the version property.

The new version dialog is appearing because the attempt to parse "GITRELEASE" into a version results in 0.0.0.0. I'd prefer to keep this functionality as a reminder that passing a proper version to `RA_Init` is expected.

**Comment by rzumer** [comment]
OK, that seems reasonable.
