### ISSUE TITLE
"Commit Selected" button remains disabled for selected entries on edit

### ISSUE THREAD

**Issue by rzumer** [RetroAchievements/RAIntegration#268]
When the `Achievement Sets` window is opened and a selected entry is modified in the editor, it seems necessary to select a different entry, and then the relevant one again in order to refresh the state of the `Commit Selected` button.

The button state should instead be refreshed after editing, or at least on window focus.

Reproduced in the `Unofficial` tab, after making a change to the badge of a selected entry.

**Comment by meleu** [comment]
I confirm this (and also think it's annoying sometimes).

**Comment by Jamiras** [comment]
I believe this has been fixed in the 0.79 DLL. Modifying a badge or the trigger immediately marks the achievement as modified and enables the Save button. You do have to click out of the text fields to mark the achievement as modified, but that's expected as the data is only updated when the field loses focus.
