### ISSUE TITLE
Enable/Disable clearing Memory Viewer when game unloaded

### ISSUE THREAD

**Issue by eldexterr** [RetroAchievements/RAIntegration#302]
The new RAIntegration have a lot of cool new features, ones that I would love to give it a try, thanks Jamiras and Syrian 😁

When I was reading the new features I saw this "bug":
• clear out memory viewer when game is unloaded

I propose this option to be a toggle if the user want it activated or not, or maybe to be like before, why?

Before the update I ever thought wasn't a bug, was very useful to be honest I thought it was a feature lol

There's is times when I'm searching a value in memory and the emulator crash and I lost all the progress I have in the memory viewer (and memory bookmarker), this is a very normal situation to be honest, especially when I'm searching a variable by freezing other ones in the memory bookmarker and the emulator can handle it and crash

I would like to propose too, if a "feature" like this can be implemented in the memory bookmarker too?

Will be very useful and I will no longer need saving a .txt of the bookmark list every 5segs if the emu crash 😅

Grettings ✌️

**Comment by Jamiras** [comment]
When a game is unloaded, the system is effectively powered off. The memory has no meaning at that point.  Attempting to modify the memory after unloading a game actually crashes some of the emulators because the associated memory has been freed.

I'm not sure that I understand what you're asking for. How would enabling the memory viewer when a game is not loaded prevent you from losing your bookmarks?

**Comment by kdecks** [comment]
I understand why this was added (as it can be used as an exploit) and yet can also see it as occasionally making development more tricky too. Most commonly during n64 development, sometimes, when searching for memory addresses I'll corrupt some memory which will cause a lockup or crash, sometimes there will be a crash even without editing memory and I'll need to reload the game but do not want to lose my current results (finding good addresses in n64 is often difficulty). I'd say this is a problem as it crashes quite often during development.

There are other times too when I might need to reload the game, but don't want to lose current search results. I can't think of an exact case, but I know that I do this sometimes.

**Comment by Jamiras** [comment]
Crashing an emulator completely destroys the process. It sounds like the game is crashing within the emulator, but the emulator itself is not crashing. I didn't know that was an option.

**Comment by eldexterr** [comment]
The game crash not the emulator sorry, the emu said something like "can't handle request" and stop the emulation and clear the memory viewer and the bookmarker too, but the emulator is still open but with any game loaded

And with the previous RAIntegration the emulation crash but the memory viewer stay the same(because that bug) and the memory bookmarker get cleaned, and I found that "bug" very useful

**Comment by rzumer** [comment]
No point in a toggle in my opinion. It is clearly useful to people for various reasons. As far as I'm concerned this was an unnecessary change and should just be reverted. I don't agree with the justification that the viewer should only be available when the system is active. It is the only way to view memory without 3rd party tools in many emulators and making it impossible to track changes between loads makes it more difficult to debug wrong triggers on load and other similar issues.

**Comment by kdecks** [comment]
Agreed.

I believe the change was made to prevent players from loading one game, then loading another which then reads as the first. This could be used for cheating.

But Jamiras just said in chat:
> one of the things i plan to do in 0.76 is overhaul the linking dialog. part of that is going to be a feature to load a game for a hash without actually associating it specifically for testing compatibility. achievement triggers will be disabled, updating notes probably too

That seems to take care of both sides of the problem.

**Comment by Jamiras** [comment]
The change was made because the memory is almost always invalid when a game is not loaded.

To unload a game on any cartridge-based system, you have to shut down the system. Many of the systems map a region of RAM associated with the cartridge SRAM. What does that look like without a cartridge loaded?

Additionally, some of the systems error out if you try to modify the memory while a game is not loaded.

I understand that this functonality may be desirable for RAQUASI and RAppleWin, which allow for the system to be running without a game loaded. But as I tried to explain when Euclide first complained, it's more important to prevent errors in the widely-used emulators than to support buggy features in the new emulators.

NOTE: This change is assuming "a game is not loaded" is reflected by the active game ID being 0. There are cases where a game may be loaded without an active game. Primarily the testing case I plan to implement in the next release.

> Perhaps it could only reset after the game id changed.

It does - it only resets when the game id changes to 0. I haven't looked into RAProject64 to see what it does when a game crashes internally, but if the memory viewer is being cleared out, it must be telling the toolkit that the game was unloaded.

**Comment by rzumer** [comment]
I think the best solution would be to fix anything "buggy" (e.g. code note submission being possible if that's the case) and allow viewing memory at all times once loaded. If some platforms don't benefit from it that's fine. There are also other emulators that can be booted without a title loaded like Gameboy (Advance) and Famicom Disk System, though I'm not sure VBA supports booting without a loaded title.

**Comment by rzumer** [comment]
Another thought I have from time to time which might be related is that I would like to be able to maintain the state of the memory inspector on unload and subsequent loads. It would help compare memory between different titles or between multiple versions of the same title, which right now can be a pain because filters and the address being pointed to are reset on subsequent loads. If the memory viewer is cleared on unload I'm not sure that remains possible.

In AppleWin, save states also include the file associated with the state, so it is necessary to unload and reload even when loading a state, thus resetting the state of the memory viewer.

**Comment by rzumer** [comment]
I made a [branch](https://github.com/rzumer/RAIntegration/tree/persist_memview) to restore some persistence, it is too annoying to work around save states not persisting the filters in RAppleWin especially. Quick hack, but good enough for my purposes.
