### ISSUE TITLE
Win32 wrong/duplicate events received after restarting the RA system

### ISSUE THREAD

**Issue by rzumer** [RetroAchievements/RAIntegration#316]
Following up on another issue I had in RAppleWin when calling RA_Shutdown() followed by a re-initialization (RA_Init()):

There is a minor issue remaining where UI buttons get stuck in the pressed state following a restart. The whole emulator UI becomes unresponsive following that, since I guess it does not expect this state to occur. This issue goes away when commenting out the call to RA_Init(). The best way I can reproduce it is switching machines in the settings and then clicking the file open dialog. It does not happen very consistently though.

I can't find anything odd on [RAW's side](https://github.com/rzumer/AppleWin/blob/cheevos/source/Frame.cpp#L1474), so it seems like wrong events are being received, like an extra mouse click. I can probably hack around it by forcefully releasing buttons after a mouse release, but it is odd that it only seems to get stuck after resetting with RA, so I am wondering if the old window handle was released correctly.

Tested both the non-RA build, RA build with the `RA_Init()` call commented out, and RA build as-is. I can only reproduce it on the last one (though not 100% of the time).

**Comment by Jamiras** [comment]
Thankfully, it's actually fairly easy to reproduce. After letting up on the mouse button, move the mouse slightly (leaving the cursor over the button) before the dialog shows up. 

The code in WM_MOUSEMOVE sees the button as active because LBUTTONUP is in the ProcessButtonClickHandler (line 1545) and hasn't cleared it yet (line 1547). Since buttondown is -1 (from line 1540), it's changed to be the active button on line 1572.

Before changing the selected system, performing these same steps does not call the WM_MOUSEMOVE handler.

I've tracked the issue down to the DLL calling `CoUninitialize` in `RA_Shutdown()`. `RA_Init()` calls `CoInitializeEx`, which because of the `CoUninitialize` is actually reloading the COM library instead of erroring with "already loaded" as occurs in the first call to `RA_Init()`. I have absolutely no idea why this impacts the `WM_MOUSEMOVE` dispatching, but will be implementing a fix that only calls `CoUninitialize` if `CoInitializeEx` doesn't return "already loaded".

**Comment by rzumer** [comment]
Strange behavior, thanks for looking into it and fixing the issue.
