### ISSUE TITLE
For AddSource / Subsource include a multiplier

### ISSUE THREAD

**Issue by kdecks** [RetroAchievements/RAIntegration#417]
So that add/sub source would work more like the ``value`` leaderboard/rich presence field include a multiplier.

The multiplier would need to be able to handled values and decimals and negatives. Being able to multiply by -1 is important for inverting a value.

This could resolve endian problems, allow a more complex combination of addresses for much higher precision, allow for weight based metrics (due to multiplier), and much more.

**Related:** It would also be valuable to be able to turn the output of any non-zero address(es) to 1 or TRUE.

I came to this often when making item based custom leaderboards like for LttP, often I'd want to turn a value to 1 (n^0), no matter what was there.. I believe this could have broad application.

**Comment by Jamiras** [comment]
The 0.79 DLL supports this.

Multiplying by a negative value is awkward, as you have to multiply by the twos-complement of the value (i.e. 0xFFFFFFFF instead of -1), but because of the way integer multiplication works, the result is still correct (see [comment](https://github.com/RetroAchievements/rcheevos/blob/6a2181c253e246b4b668c92e787120edd7e4d512/src/rcheevos/condition.c#L250-L255)).
