### ISSUE TITLE
Remove Hit Target requirement from AddHits Flag (or create a new flag?)

### ISSUE THREAD

**Issue by eldexterr** [RetroAchievements/RAIntegration#432]
Hi, right now to use the AddHits flag you need to have a Hit Counter to the new Non-AddHits condition to make the flag work

I think will be a better Idea to remove that requirement because that just create new options to create achievements more easily, I got to this conclution when making an achievement for MGS1 (PSX)

![Captura](https://user-images.githubusercontent.com/44853315/63288802-749cbc80-c272-11e9-9dc9-00f6dd725028.PNG)

For example here I want the achievement to trigger if any of the AddHits conditions are true
I can use the AddHits flag by adding a Hit Target for the last condition, but that just will complicate a lot the logic because now I need to add a Reset to reset the hit counter for the last condition (complicating another parts of the logic because of that as I said before)

Using this method also will save me some time because right know the achievement will have 24 Alts   (4 to track each NPC coordinates (+X Axis, -X Axis, +Z Axis, -Z Axis) multiply that for 3 because there is 3 NPCs ID, now I have 12 Alts and multiply that by 2 to add support for the 1.1 version for the game, thats 24 alts!)(without adding the Reset to the logic btw)

And with this method I will need only to use 6 Alts! (3 for every NPC ID and other 3 to add support for the 1.1 version) and without needing to add the Reset making the achievement more harder to code, that's a big diference

I hope my message will be completely clear, greetings :)

**Comment by Jamiras** [comment]
The concept is to use `Add Hits` like an `OrNext`, but it will fail for the same reasons that you don't want to add a `Hit Target` to the final condition - the sub-condition `Hit Count`s need to be reset on frames where the condition is false.

Each sub-condition tracks its hits independently, and `Add Hits` just sums them up to reach the final `Hit Target`. There's nothing indicating whether or not the individual sub-conditions are _currently_ true.

In your example, the `Add Hits` tally is explicitly ignored in Condition 9 because it doesn't have a `Hit Target`, effectively making Conditions 5-8 irrelevant. 

If we didn't explicitly ignore it, Condition 9's `Hit Count` would be added to the `Add Hits` tally and compared against Condition 9's `Hit Target`. In the case where Condition 9's `Hit Target` is 0, if any of the three sub-conditions had a `Hit Count`, Condition 9 would be true, and would remain true until the relevant sub-conditions had their `Hit Count` reset. There would be no difference between having a `Hit Target` of 0 or a `Hit Target` of 1.

I don't think it's desirable to use `Add Hits` in this manner. If we're going to introduce new behavior, we might as well make it clear by providing an `OrNext`. `Add Hits`, and `Hit Target`s in general, are designed for keeping track of things that happened in the past. You only care about things that are happening now.

**Comment by eldexterr** [comment]
Fixing this issue solved was I was asking for: https://github.com/RetroAchievements/RAIntegration/issues/422#issuecomment-548642557
