### ISSUE TITLE
Make AddHits not require a hit target to work

### ISSUE THREAD

**Issue by Blazekickn** [RetroAchievements/RAIntegration#476]
Currently AddHits only works if there is a hit target, like this:
![image](https://user-images.githubusercontent.com/38176599/68103126-9554d580-fea3-11e9-8563-842ced183a59.png)

**Comment by Blazekickn** [comment]
helpful for being able to use AddHits as an or condition for stuff like checking inventory without needing a billion alt groups.
![image](https://user-images.githubusercontent.com/38176599/68103859-7572e100-fea6-11e9-919c-d1c2e7347cc1.png)

**Comment by Jamiras** [comment]
OrNext would be the preferred solution (#462). It's much clearer what the intent of the code is.

**Comment by Blazekickn** [comment]
even if we have OrNext i dont really see why AddHits arbitrarily needs a hit target. Its still adding hits.

**Comment by Jamiras** [comment]
The problem with evaluating AddHits without a hit target is that it would be affected by history.

Given your example above, lines 1-3 are attempting to create a trigger that fires if any of the first three bytes are 0x69, and lines 4-6 are doing the same for 0x420 (which can never be true because it's more than can be represented by 8-bits, but that's not important for this discussion).

If we change the behavior such that the end of an AddHits chain doesn't require a hit target, this is what would happen:
* Assuming byte 2 is 0x69 in the first frame line 2 would gain a hit and condition 3 would be true because there isn't a hit target. Since line 6 is not true, the achievement wouldn't trigger.
* In the next frame, byte 2 is no longer 0x69, but it still has a captured hit from the first frame. As a result, the AddHits sum will be non-zero, so line 3 would be treated as true.
* At this point, line 3 will remain true until a ResetIf clears the hit count, which is not the desired behavior if you're really trying to use AddHits to simulate an OrNext.

OrNext would only return true if any of the joined statements _were currently_ true.

AddHits without a hit target is not a suitable replacement for OrNext. If you want the behavior that not having a hit target would provide, you can just set the hit target to 1. As soon as any condition in the chain is true, the entire chain will be true indefinitely.

I'm going keep this issue open for now as a reminder to add validation and inform a user who tries to use AddHits without a hit target that it won't work they way they expect.
