### ISSUE TITLE
[Suggestion] Add Missable Achievement Notification

### ISSUE THREAD

**Issue by eldexterr** [RetroAchievements/RAIntegration#508]
We got Measured (very cool feature), I was thinking, what about a way to make a notification pop-up when a missable achievement can be triggered?

The notification can use a diferent color (like the mastery one) so the player doens't think he just earned an achievement, also an option to disable this notifications, maybe they're players who doesn't want to get kind of spoiled by the notifications

**Comment by Sanaki** [comment]
I actually was just coming here to suggest this same thing, and then some. To be specific, I'd like to see support added for a secondary "achievement" type that's purely informational. Preferably that could trigger multiple times in a single session, similar to a leaderboard, but I don't know how viable that is. I'd actually put missables as a subcategory of the information type, primarily for the purpose of being able to add toggles to the achievements menu to disable all information popups (for those who may not want to see them at all), and further being able to leave them enabled but still disable missable notices for players who dislike seeing that sort of "spoiler".

The inspiration for this was [this achievement](https://retroachievements.org/achievement/82088), which pops on the title screen just to deliver information.

**Comment by Keltron3030** [comment]
Seems that you could use a leaderboard for that function right now.

**Comment by Sanaki** [comment]
Leaderboards would work in place of the achievement I linked, but not being able to toggle that specific type off would be problematic for the interest level I was hearing in discord chat. Some people want to use them for frequent info popups, which should be something a player can easily opt out of without losing functionality. Same goes for missables, since some players don't want to know about them.
