### ISSUE TITLE
Ability to manually reset an achievement

### ISSUE THREAD

**Issue by meleu** [RetroAchievements/RAIntegration#7]
_From @Jamiras on March 21, 2018 15:3_

As a developer, I'd like to explicitly reset all the HitCounts in an achievement to 0. Suggest adding a button to the achievement editor to do so.

_Copied from original issue: RetroAchievements/RASuite#60_

**Comment by meleu** [comment]
_From @kdecks on April 8, 2018 4:33_

I've found a quick way to do this is deactivate and then reactivate the individual achievement. (This only works in local and unofficial)

**Comment by eldexterr** [comment]
I would love this!

**Comment by Keltron3030** [comment]
For what purpose, toubleshooting/ticket resolution in core?

**Comment by eldexterr** [comment]
There's sometimes I want to reset the hit count while fixing a ticket, the only solution I have is to use the "Revert Selected" button to reset the hit, but there's sometimes when I can't revert because I made some changes to the logic

Usually in that case I copy the achievement to local, to be able to activate and deactivate the achievement so I can reset the hits by doing that

**Comment by Jamiras** [comment]
> I've found a quick way to do this is deactivate and then reactivate the individual achievement. (This only works in local and unofficial)

You can now deactivate core achievements (if not in hardcore mode). And this does cause all hits to be reset to 0 when the achievement is reactivated.
