### ISSUE TITLE
Leaderboard updates can be published with no changes

### ISSUE THREAD

**Issue by Tsearo** [RetroAchievements/RAIntegration#886]
Current behavior - Make an update to a leaderboard, undo change manually
Leaderboard shows as modified and allows user to publish "changes"

Expected behavior - Make an update to a leaderboard, undo change manually
Leaderboard no longer shows modified and cannot be saved and published

Example:
Original
![image](https://user-images.githubusercontent.com/4047771/166078081-83d09206-3d1b-4ee9-b858-9b6f1ba3f395.png)

Add new condition to Start - Shows as modified and can Save changes
![image](https://user-images.githubusercontent.com/4047771/166078094-9f58793d-bcc1-41e0-a67d-409f48fb3dd4.png)

Remove the newly added condition - Can still Save changes as well as Publish afterwards
![image](https://user-images.githubusercontent.com/4047771/166078132-18e511e1-6219-475f-9643-947045494afd.png)

I tested it just to be sure and the "changes" do go through and get pushed to the site. I'm assuming there is some check for achievements to compare local vs core to determine if it has been modified, possibly this method does not work well for leaderboards? If this is not something easily fixable on the RAIntegration end I can look into ignoring update messages if there are no changes found on the web end of things.

**Comment by Jamiras** [comment]
It's looking for an exact match. If the leaderboard definition entered into the site isn't exactly what the serializer generates, it'll say it's Modified. For example, I was modifying a leaderboard from Super Mario Bros. The site says:
```
0xh75c=h1_0xh75f=h0_0xh770=h01_0xh71a=h00_0xh757=h0
```
But when I make a modification and undo it, the thing that gets generated is:
```
0xH075c=1_0xH075f=0_0xH0770=1_0xH071a=0_0xH0757=0
```
Notice that the hex constants are converted to decimal constants (`h1` and `h01` to `1` and `h0` and `h00` to `0`), and therefore the record appears modified. Also, the three character addresses are converted to four characters and the size identifier is uppercased (`0xh75c` to `0xH075c`).

This commonly occurs when editing the Value field as the new value definition is always in Measured format (`A:0xH1235*100_M:0xH1234` instead of `0xH1235*100_0xH1234`).

Could you have maybe encountered one of these non-functional changes? If not, could you provide the "before" serialized value? If it's truly unmodified it should also be the "after" serialized value.

**Comment by Tsearo** [comment]
Yep that sounds like what is happening then, I was checking an old leaderboard that I wrote out manually so it makes sense that it wouldn't match what is generated from RAIntegration.

Value:
Original - `0xHc0b3*60_0xHc0a4`
RALib - `A:0xH00c0b3*60_M:0xH00c0a4`

Doesn't seem like there would be a good way to handle this really in RAIntegration or on the site since there likely isn't a way to test that two fields are functionally equivalent so I'm fine with this issue being closed out if you agree.
