### ISSUE TITLE
Addresses in Memory boomarks should not be sorted alphabetically

### ISSUE THREAD

**Issue by suXinjke** [RetroAchievements/RAIntegration#900]
RAIntegration 1.0.4

On screenshot below I clicked on Address column to sort ascending, but it doesn't respect addresses being numeric, they're sorted alphabetically instead

```
0x1ffa408
0x241174 this value should be above, but it isn't
```

In the end it doesn't match sorted Code notes RAWeb page, which is a minor issue. Sometimes you seek for bookmark based on it's memory region.

![image](https://user-images.githubusercontent.com/9765719/170709063-0df1b1b8-268f-4fd7-8abe-5372687d6d5d.png)

**Comment by suXinjke** [comment]
Alternate solution is to make it pad all the addresses with zeroes

**Comment by Jamiras** [comment]
It does pad the address - to 4 character if the total memory <= 64KB otherwise to 6 characters.
![image](https://user-images.githubusercontent.com/32680403/170711961-f368b19c-f2fe-40c3-89ea-79afb07b97ef.png)
![image](https://user-images.githubusercontent.com/32680403/170712631-1468bc60-1d0b-4085-a3c8-fd7e566725af.png)

You're just using a system where 6 characters is not enough.
