### ISSUE TITLE
Comments cannot be added to the display string in RP, because of how empty lines are handled

### ISSUE THREAD

**Issue by Fretzi** [RetroAchievements/RAIntegration#939]
When attempting to add comments onto anywhere inside the display string of your RP script, the RP monitor spits out a Parse error -18.
This is likely because comment lines are handled similar as empty lines, which causes the exact same error.
Here is an example of me adding comment lines and the thus resulting error.
![image](https://user-images.githubusercontent.com/48097547/199557355-509c4222-9c43-4626-b55c-b7fdedfd03b8.png)

Pay attention to how it points to line 68 as the source of the issue, which is the very bottom of the file, here in the form of a simple comment.
All I have to do is remove the test comment and the script works fine again.
Seems to very much not be intentional, as the docs state "Comments can be added anywhere in the script."
Also don't know if I should emphasize again how any empty line inside the display string breaks the script in the same way.

**Comment by Jamiras** [comment]
Comments are stripped from the end of each line, leaving a blank display string, which causes the error. I'll correct for that. It is intentional that empty lines are not allowed as empty lines are separators between sections (`Format:`, `Lookup:`, `Display:`).

The line associated with a missing display string is always the last line of the file, as we only check to see if a display string was found after the rest of the file has been successfully processed. I should be able to modify it to report the line of the `Display:` directive if it was seen.
